
image: node:latest

build-backend:
  stage: build
  script:
    - cd backend
    - npm install
  after_script:
    - cd ..

test-backend:
  stage: test
  script:
    - cd backend
    - npm run test
  after_script:
    - cd ..

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm install
  after_script:
    - cd ..

test-frontend:
  stage: test
  script:
    - cd frontend
    - npm test
  after_script:
    - cd ..