image: node:latest

cache:
  paths:
    - backend/node_modules/
    - frontend/node_modules/

test_backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
  after_script:
    - cd ..

build_frontend:
  stage: build
  script:
    - cd frontend
    - 
  after_script:
    - cd ..

test_frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test
  after_script:
    - cd ..
    
