test_backend:
  image: node:latest
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
  after_script:
    - cd ..

test_frontend:
  image: node:latest
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test
  after_script:
    - cd ..