services:
- type: web
  plan: free
  name: fast-friends-be
  env: node
  rootDir: backend
  buildCommand: npm install && npm run typeorm migration:run -- -d src/data-source.ts
  startCommand: npx @nestjs/cli start
  envVars:
    - key: NODE_ENV
      value: prod
    - key: PORT
      value: "4000"
    - key: DATABASE_HOST
      fromDatabase:
        name: fast-friends-prod
        property: host
    - key: DATABASE_PORT
      fromDatabase:
        name: fast-friends-prod
        property: port
    - key: DATABASE_USER
      fromDatabase:
        name: fast-friends-prod
        property: user
    - key: DATABASE_PASSWORD
      fromDatabase:
        name: fast-friends-prod
        property: password
    - key: DATABASE_NAME
      fromDatabase:
        name: fast-friends-prod
        property: database
- type: web
  name: fast-friends
  runtime: static
  rootDir: frontend
  buildCommand: npx expo export -p web
  staticPublishPath: dist
  domains:
    - fast-friends.biz
    - www.fast-friends.biz
  routes:
    - type: redirect
      source: /*
      destination: /index.html
  envVars:
    - key: BASE_URL
      fromService:
        type: web
        name: fast-friends
        property: host

databases:
  - name: fast-friends-prod
    databaseName: fast_friends_prod
    user: fast_friends_prod_user
    plan: free

