POST http://localhost:3000/auth/create HTTP/1.1
content-type: application/json

{
    "username": "stupid@user.com",
    "password": "st^pidUser"
}

###

GET https://fast-friends.onrender.com/ HTTP/1.1
content-type: application/json

{

}

###

GET https://fastfriends.biz/ HTTP/1.1
content-type: application/json

{

}

###

GET https://www.strava.com/api/v3/athlete
Authorization: Bearer 3aaf866e4d84a05dbe11d27468cb825ab04abe64
###

GET https://www.strava.com/api/v3/athlete
Authorization: Bearer 4feedc91c8a28d3e4de36165a227278d3511cbd0

###
GET https://www.strava.com/api/v3/athlete/activities
Authorization: Bearer 3aaf866e4d84a05dbe11d27468cb825ab04abe64

###
GET https://www.strava.com/api/v3/gear/b11575838
id: 10352896
Authorization: Bearer 4feedc91c8a28d3e4de36165a227278d3511cbd0
###
b11575838
####
GET https://www.strava.com/api/v3/gear/10352896
id: 10352896
Authorization: Bearer 9a830a43bd78fd6c62837f6596d83011fe537f64

### Refresh 7128
POST https://www.strava.com/api/v3/oauth/token
client_id: 125563
client_secret: 22bbcc919c35ee62b0a8882def9503b459a39341
refresh_token: f1bfa76918a3f57a612a6af6b358a6f0e5ef6316
grant_type: refresh_token

####
POST https://www.strava.com/oauth/token?client_id=125563&client_secret=22bbcc919c35ee62b0a8882def9503b459a39341&code=81825239942181a4090c1639f2180b430325bc60&grant_type=authorization_code

###
http://www.strava.com/oauth/authorize?client_id=125563&response_type=code&redirect_uri=http://localhost/exchange_token&approval_prompt=force&scope=read_all,profile:read_all

##
 -X POST https://www.strava.com/oauth/token \
    -F client_id=125563 \
###
http://localhost/exchange_token?state=&code=c6687080f506537d8b6a63ef30827bc316798ae3&scope=read,read_all
curl -X POST https://www.strava.com/oauth/token \
	-F client_id=125563 \
	-F client_secret=22bbcc919c35ee62b0a8882def9503b459a39341 \
	-F code=1306d5b66beef43a0146eedb10c1bcaf41bd6206 \
	-F grant_type=authorization_code