POST http://localhost:3000/auth/create HTTP/1.1
content-type: application/json

{
    "username": "stupid@user.com",
    "password": "st^pidUser"
}

###

GET https://fast-friends.onrender.com/ HTTP/1.1
content-type: application/json

{

}

###

GET https://fastfriends.biz/ HTTP/1.1
content-type: application/json

{

}

###